file_format: "1"
id: tps40
name: TPS40
type: shield
url: https://github.com/crehmann/TPS40
requires: [pro_micro]
exposes: [spi_lcd]
features:
  - keys
  - display
siblings:
  - tps40_left
  - tps40_right
